{% set name = "segment-geospatial" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-geospatial-{{ version }}.tar.gz
  sha256: 91ff1c265936bd85ac2b6489db5b97299238269e70bc3d53314bf6f725631e0c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - onnxruntime
    - onnx
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xyzservices
    - pyproj

test:
  imports:
    - samgeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://geosam.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
