{% set python_min = "3.10" %}
{% set name = "segment-geospatial" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/segment_geospatial-{{ version }}.tar.gz
  sha256: 6768986ad48ad0f5ff45fd921496e05fd6b8f1f0cdd762358b9b723e3e68d73b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - huggingface_hub
    - fiona
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xarray
    - xyzservices
    - pycrs
    - pyproj
    - leafmap
    - localtileserver
    - rioxarray
    - sam3
    - scikit-image
    - scikit-learn
    - timm
    - patool
    - ipympl
    - transformers
    - buildingregulariser
    - spacy


test:
  imports:
    - samgeo
  # commands:
  #   - pip check
  requires:
    - pip
    - libopencv *=headless*  # [linux]
    - python {{ python_min }}

outputs:
  - name: segment-geospatial
  - name: samgeo
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("segment-geospatial", exact=True) }}

    test:
      imports:
        - samgeo
      requires:
        - pip
        - libopencv *=headless*  # [linux]
        - python {{ python_min }}
about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://samgeo.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
