{% set name = "segment-geospatial" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8ce07c12b2a6de1de61c1d6cc5b2eaf4f5e9122e8c7bc010ea248cc3ed86738d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - huggingface_hub
    - fiona
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xarray
    - xyzservices
    - pycrs
    - pyproj
    - leafmap
    - localtileserver
    - sam2
    - segment-anything-hq
    - timm
    - patool
    - ipympl

test:
  imports:
    - samgeo
  # commands:
  #   - pip check
  requires:
    - pip
    - libopencv *=headless*  # [linux]

outputs:
  - name: segment-geospatial
  - name: samgeo
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("segment-geospatial", exact=True) }}

    test:
      imports:
        - samgeo
      requires:
        - pip
        - libopencv *=headless*  # [linux]
        
about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://geosam.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
