{% set name = "segment-geospatial" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bc75e8e8756a284b7d4fe65a9b3d0f6dc4be5c0c33b22c2eb2900157194e721f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - huggingface_hub
    - fiona
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xarray
    - xyzservices
    - pycrs
    - pyproj
    - leafmap
    - localtileserver
    - rioxarray
    - sam2
    - scikit-image
    - scikit-learn
    - segment-anything-hq
    - timm
    - patool
    - ipympl

test:
  imports:
    - samgeo
  # commands:
  #   - pip check
  requires:
    - pip
    - libopencv *=headless*  # [linux]

outputs:
  - name: segment-geospatial
  - name: samgeo
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("segment-geospatial", exact=True) }}

    test:
      imports:
        - samgeo
      requires:
        - pip
        - libopencv *=headless*  # [linux]
about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://samgeo.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
