{% set name = "segment-geospatial" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/segment-geospatial-{{ version }}.tar.gz
  sha256: 2fd80b8990d5d19e212c1d94fb20147432c42271c82ea250ddbaa3d88ae91f72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - huggingface_hub
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xyzservices
    - pyproj
    - leafmap
    - localtileserver
    - segment-anything-hq
    - timm

test:
  imports:
    - samgeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://geosam.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
