{% set name = "segment-geospatial" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02986494eb820c8386e8fa415578336ea4b81b0e4a4957912de506fda872ddcb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - segment-anything
    - opencv
    - pycocotools
    - matplotlib-base
    - huggingface_hub
    - geopandas
    - rasterio
    - tqdm
    - gdown
    - xarray
    - xyzservices
    - pyproj
    - leafmap
    - localtileserver
    - segment-anything-hq
    - timm
    - patool

test:
  imports:
    - samgeo
  commands:
    - pip check
  requires:
    - pip
    - libopencv *=headless*  # [linux]

about:
  home: https://github.com/opengeos/segment-geospatial
  summary: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  description: A Python package for segmenting geospatial data with the Segment Anything Model (SAM)
  doc_url: https://geosam.gishub.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
